version: '3.1'

services:
  node:
    restart: always
    build: .
    ports:
      - 8088:3000
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8084:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/